- LICENSE
- NOTICE
- README.md
> initial setup

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/dependabot.yml
- .github/workflows/build.yaml
- .github/workflows/cloc.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/dco.yml
- .github/workflows/scorecards.yml
- .github/workflows/stale.yaml
> initial commit for workflows

- .github/workflows/codeql-analysis.yml
> fix workflow

- images/ubuntu/static.yaml
> initial commit for the static image

- .github/workflows/build.yaml
> fix workflow to publish images

- .github/workflows/build.yaml
> fix workflow to push and sign images

- .github/workflows/build.yaml
- README.md
- pkgmgr/defs.sh
> fix arch support in build

- .github/workflows/build.yaml
- images/base/LICENSE.md
- images/base/README.md
- images/devel/LICENSE.md
- images/devel/Makefile
- images/devel/README.md
- images/devel/debian-pkgs.sh
- images/devel/rockylinux-pkgs.sh
- images/devel/stacker.yaml
- images/devel/ubuntu-pkgs.sh
- images/go-devel/LICENSE.md
- images/go-devel/README.md
- images/go-devel/stacker.yaml
- images/openj9-devel/LICENSE.md
- images/openj9-devel/README.md
- images/openj9-devel/stacker.yaml
- images/openj9/LICENSE.md
- images/openj9/README.md
- images/openj9/stacker.yaml
- images/static/LICENSE.md
- images/static/README.md
- images/test/test.py
- pkgmgr/defs.sh
> add annotations

- images/base/README.md
- images/devel/README.md
- images/go-devel/README.md
- images/openj9-devel/README.md
- images/openj9/README.md
- images/static/README.md
> fix image descriptions

- .github/workflows/build.yaml
> fix annotations workflow

- .github/workflows/dco.yml
- .github/workflows/scorecards.yml
> fix dco check workflow to allow squash/merge

- .github/workflows/build.yaml
- .github/workflows/commit-msg.yaml
- .github/workflows/scorecards.yml
- .github/workflows/stale.yaml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
> chore: update README.md, docs and workflows

- .github/workflows/commit-msg.yaml
- .github/workflows/scorecards.yml
- .github/workflows/shellcheck.yaml
> chore: fix dependabot alerts

- .github/workflows/build.yaml
> feat: also build squashfs images

- .github/workflows/build.yaml
- .github/workflows/scorecards.yml
> fix(ci): fix the release workflow

- .github/workflows/build.yaml
> fix(ci): fix the image that is signed by cosign

- .github/workflows/build.yaml
> fix(ci): also cosign squashfs images

- .github/workflows/build.yaml
- images/multitool/helloworld.txt
> build: fix release build for 'multitool' image

- .github/workflows/build.yaml
> build(creds): change the way zothub credentials are passed to stacker

- .github/workflows/build.yaml
- config.mk
- images/base/Makefile
- images/devel/Makefile
- images/go-devel/Makefile
- images/multitool/Makefile
- images/openj9-devel/Makefile
- images/openj9/Makefile
- images/static/Makefile
> fix(publish): fix image publishing logic

- config.mk
> fix(creds): quote credentials when pushing

- .github/workflows/build.yaml
Cleanup leftover from the refactoring.
> fix(release): remove unneeded build step

- .github/workflows/build.yaml
Consistency with PR jobs.
Also we need to build a matrix of: ubuntu, debian, rocky. So this will same some time.
> build(parallel): for build+publish jobs allow 3 jobs in parallel

- CODEOWNERS
> doc: add CODEOWNERS file

- .github/workflows/build.yaml
> ci(deps): fix a quoting issue in determining affected images

- Makefile
- config_rust.mk
- image_deps.json
- images/rust-devel/LICENSE.md
- images/rust-devel/Makefile
- images/rust-devel/README.md
- images/rust-devel/debian-pkgs.sh
- images/rust-devel/rockylinux-pkgs.sh
- images/rust-devel/stacker.yaml
- images/rust-devel/ubuntu-pkgs.sh
- images/static/stacker.yaml
- images/test/test.rs
- pkgmgr/defs.sh
Also fix an issue where the certificates from the ca-certificates package
were not present in the final images
> feat(new image): add rust image
